
*** Adding controller

** Adding Switches

** Creating Links 
(1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit 2.5ms delay) (1.00Mbit 80.00000% loss) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit 2.5ms delay) *** Configuring hosts
ht hu it iu rh ri 
*** Starting controller
c0 
*** Starting 2 switches
sw1 () () () sw2 () () () ...() () () () () () 

*** Configuring hosts

*** Running CLI
*** Starting CLI:
File already exists.
containernet> Traceback (most recent call last):
  File "network-ephemeral-rtt5-buffer100-bw1-loss10.py", line 200, in <module>
    createNetwork()
  File "network-ephemeral-rtt5-buffer100-bw1-loss10.py", line 186, in createNetwork
    CLI(net)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.3.1-py2.7.egg/mininet/cli.py", line 71, in __init__
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.3.1-py2.7.egg/mininet/cli.py", line 104, in run
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
IOError: [Errno 9] Bad file descriptor

*** Adding controller

** Adding Switches

** Creating Links 
(1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit 2.5ms delay) (1.00Mbit 80.00000% loss) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit) (1.00Mbit 2.5ms delay) *** Configuring hosts
ht hu it iu rh ri 
*** Starting controller
c0 
*** Starting 2 switches
sw1 () () () sw2 () () () ...() () () () () () 

*** Configuring hosts

*** Running CLI
*** Starting CLI:
File already exists.
containernet> Traceback (most recent call last):
  File "network-ephemeral-rtt5-buffer100-bw1-loss10.py", line 200, in <module>
    createNetwork()
  File "network-ephemeral-rtt5-buffer100-bw1-loss10.py", line 186, in createNetwork
    CLI(net)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.3.1-py2.7.egg/mininet/cli.py", line 71, in __init__
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.3.1-py2.7.egg/mininet/cli.py", line 104, in run
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
IOError: [Errno 9] Bad file descriptor
